language: go

go:
    - 1.3
    - tip

before_install:
  - go get github.com/tools/godep
  - go install -race std

script: 
  - godep go test -race ./models 
  - godep go test -race ./proxy/router 
  - godep go test -race ./proxy/router -broker="ledisdb"

